spring.application.name=trading-post-service
# === SPRINGDOC OPENAPI CONFIGURATION ===

# API Docs base path (JSON spec)
springdoc.api-docs.path=/v3/api-docs

# Swagger UI web path
springdoc.swagger-ui.path=/swagger-ui
springdoc.paths-to-match=/api/**
# Optional: limit Swagger scanning to specific controller package
springdoc.packages-to-scan=com.tps.controller

# --- Common JPA/Hibernate ---
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hikari common
spring.datasource.hikari.pool-name=HikariCP

# Let each profile provide its own URL and credentials
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Default profile if none set (optional)
# spring.profiles.default=dev


logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
logging.level.org.springframework.web=DEBUG

