# Example: QA RDS
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2


security.ip-allowlist=srv1095460.hstgr.cloud,191.101.81.225,122.177.246.94