spring.application.name=trading-post-service

# === SPRINGDOC OPENAPI CONFIGURATION ===

# API Docs base path (JSON spec)
springdoc.api-docs.path=/v3/api-docs

# Swagger UI web path
springdoc.swagger-ui.path=/swagger-ui
springdoc.paths-to-match=/api/**
# Optional: limit Swagger scanning to specific controller package
springdoc.packages-to-scan=com.tps.controller

# --- Common JPA/Hibernate ---
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hikari common
spring.datasource.hikari.pool-name=HikariCP

# Let each profile provide its own URL and credentials
#spring.datasource.url=${DB_URL:}
#spring.datasource.username=${DB_USERNAME:}
#spring.datasource.password=${DB_PASSWORD:}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Token settings
security.token.issuer=trading-post-service
security.token.secret=0CqcPIP+z/slxdDVC9WyUkluKjpS9OWyvCRyW04F8F0=
# 6 hours
security.token.access-validity-seconds=21600
 # 7 days 
security.token.refresh-validity-seconds=604800
security.token.reuse-same-access-token=true

# IP allowlist (exact IPs or CIDR ranges)
security.ip-allowlist=0:0:0:0:0:0:0:1,127.0.0.1,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

# Default profile if none set (optional)
spring.profiles.default=local


logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
logging.level.org.springframework.web=DEBUG

