
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Smaller pool for local work
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# Dev logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=DEBUG
logging.level.com.tps.service=INFO
logging.level.com.tps.controller=INFO
logging.level.com.tps.cache.events=INFO
app.root.tokenId=TRADEPOSTAPP-9af31bc59e

security.ip-allowlist=srv1095460.hstgr.cloud,191.101.81.225,122.177.246.94,103.160.27.6
 
