# Example: Prod RDS \u2013 SSL on, no schema changes
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5

# Safer timeouts
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000


security.ip-allowlist=srv1095460.hstgr.cloud,191.101.81.225,122.177.246.94

