# Local uses local DB and can auto-update schema
spring.datasource.url=jdbc:mysql://localhost:3306/tpsdb_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=tpsuser
spring.datasource.password=brahma2242@pP

# 1. Disable explicit SQL printing
spring.jpa.show-sql=false

# 2. Set the root log level high (WARN)
logging.level.root=WARN

# 3. Explicitly suppress Hibernate SQL logging packages
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

# 4. Enable custom service/cache packages at INFO level for testing
logging.level.com.tps.service.FirmService=INFO
logging.level.com.tps.service.DomainService=INFO
logging.level.com.tps.cache.events=INFO
server.port=9098
app.root.tokenId=TRADEPOSTAPP-9af31bc59e
