package com.tps.enums;

public enum EventChangeType {
	FIRM_CREATED, FIRM_UPDATED, FIRM_DELETED,

	REVIEW_CREATED, REVIEW_UPDATED, REVIEW_DELETED,

	CHALLENGE_CREATED, CHALLENGE_UPDATED, CHALLENGE_DELETED;

}
